### ISSUE TITLE
Drax starting issue

### ISSUE THREAD

**Issue by normski72** [stevie910/drax#12]
On start up I’m greeted with the donate box, due to old laptop and dodgy mouse managed to click donated already, now the application won’t launch (briefly launches and then straight off, fraction of a second). Even after deleting the app and reinstalling problem still persists, any help you can give would be greatly appreciated as I haven’t even had chance to use it yet.

**Comment by stevie910** [comment]
That sounds strange, because Drax should start smoothly, if you have clicked "already donated". It doesn't matter if you have actually donated or not. There is no detailed validation.

What you can try is to 1) uninstall Drax again, 2) additionally delete the corresponding registry key, that is, "HKEY_CURRENT_USER\Software\drax", and 3) install Drax again.

Hope this helps.

**Comment by normski72** [comment]
Thanks for the reply I appreciate it. It turns out it’s my fault it wouldn’t work, I wanted to install it in a folder with all my dvd tools. Uninstalled it and reinstalled it the folder it chose and now it works fine. Thank you
